version: "3"

services:

  app:
    image: wadoz/rest
    restart: always
    depends_on:
    - mysql
    ports:
    - "8081:8080"

  mysql:
    image: mysql:8.0.12
    environment:
      MYSQL_USER: wadoz
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "3308:3306"