version: "3.2"

services:

  mysql:
    container_name: 'mysql-connect'
    image: mysql:8.0.12
    environment:
      MYSQL_USER: wadoz
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
